//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SITGPIntegrationModel", "FK_TransaccionVenta_CargaGP", "CargaGP", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SITCASH_EXE_PS.MODEL.CargaGP), "TransaccionVenta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SITCASH_EXE_PS.MODEL.TransaccionVenta), true)]

#endregion

namespace SITCASH_EXE_PS.MODEL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SITGPIntegrationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SITGPIntegrationEntities object using the connection string found in the 'SITGPIntegrationEntities' section of the application configuration file.
        /// </summary>
        public SITGPIntegrationEntities() : base("name=SITGPIntegrationEntities", "SITGPIntegrationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SITGPIntegrationEntities object.
        /// </summary>
        public SITGPIntegrationEntities(string connectionString) : base(connectionString, "SITGPIntegrationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SITGPIntegrationEntities object.
        /// </summary>
        public SITGPIntegrationEntities(EntityConnection connection) : base(connection, "SITGPIntegrationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CargaGP> CargaGP
        {
            get
            {
                if ((_CargaGP == null))
                {
                    _CargaGP = base.CreateObjectSet<CargaGP>("CargaGP");
                }
                return _CargaGP;
            }
        }
        private ObjectSet<CargaGP> _CargaGP;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HCargaGP> HCargaGP
        {
            get
            {
                if ((_HCargaGP == null))
                {
                    _HCargaGP = base.CreateObjectSet<HCargaGP>("HCargaGP");
                }
                return _HCargaGP;
            }
        }
        private ObjectSet<HCargaGP> _HCargaGP;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TransaccionVenta> TransaccionVenta
        {
            get
            {
                if ((_TransaccionVenta == null))
                {
                    _TransaccionVenta = base.CreateObjectSet<TransaccionVenta>("TransaccionVenta");
                }
                return _TransaccionVenta;
            }
        }
        private ObjectSet<TransaccionVenta> _TransaccionVenta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TransaccionVentaItem> TransaccionVentaItem
        {
            get
            {
                if ((_TransaccionVentaItem == null))
                {
                    _TransaccionVentaItem = base.CreateObjectSet<TransaccionVentaItem>("TransaccionVentaItem");
                }
                return _TransaccionVentaItem;
            }
        }
        private ObjectSet<TransaccionVentaItem> _TransaccionVentaItem;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CargaGP EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCargaGP(CargaGP cargaGP)
        {
            base.AddObject("CargaGP", cargaGP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HCargaGP EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHCargaGP(HCargaGP hCargaGP)
        {
            base.AddObject("HCargaGP", hCargaGP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TransaccionVenta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransaccionVenta(TransaccionVenta transaccionVenta)
        {
            base.AddObject("TransaccionVenta", transaccionVenta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TransaccionVentaItem EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransaccionVentaItem(TransaccionVentaItem transaccionVentaItem)
        {
            base.AddObject("TransaccionVentaItem", transaccionVentaItem);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SITGPIntegrationModel", Name="CargaGP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CargaGP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CargaGP object.
        /// </summary>
        /// <param name="iDCarga">Initial value of the IDCarga property.</param>
        /// <param name="estatus">Initial value of the Estatus property.</param>
        public static CargaGP CreateCargaGP(global::System.Int32 iDCarga, global::System.String estatus)
        {
            CargaGP cargaGP = new CargaGP();
            cargaGP.IDCarga = iDCarga;
            cargaGP.Estatus = estatus;
            return cargaGP;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCarga
        {
            get
            {
                return _IDCarga;
            }
            set
            {
                if (_IDCarga != value)
                {
                    OnIDCargaChanging(value);
                    ReportPropertyChanging("IDCarga");
                    _IDCarga = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCarga");
                    OnIDCargaChanged();
                }
            }
        }
        private global::System.Int32 _IDCarga;
        partial void OnIDCargaChanging(global::System.Int32 value);
        partial void OnIDCargaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDVendedor
        {
            get
            {
                return _IDVendedor;
            }
            set
            {
                OnIDVendedorChanging(value);
                ReportPropertyChanging("IDVendedor");
                _IDVendedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDVendedor");
                OnIDVendedorChanged();
            }
        }
        private global::System.String _IDVendedor;
        partial void OnIDVendedorChanging(global::System.String value);
        partial void OnIDVendedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDAyudante
        {
            get
            {
                return _IDAyudante;
            }
            set
            {
                OnIDAyudanteChanging(value);
                ReportPropertyChanging("IDAyudante");
                _IDAyudante = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDAyudante");
                OnIDAyudanteChanged();
            }
        }
        private global::System.String _IDAyudante;
        partial void OnIDAyudanteChanging(global::System.String value);
        partial void OnIDAyudanteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDAyudante2
        {
            get
            {
                return _IDAyudante2;
            }
            set
            {
                OnIDAyudante2Changing(value);
                ReportPropertyChanging("IDAyudante2");
                _IDAyudante2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDAyudante2");
                OnIDAyudante2Changed();
            }
        }
        private global::System.String _IDAyudante2;
        partial void OnIDAyudante2Changing(global::System.String value);
        partial void OnIDAyudante2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDFactura
        {
            get
            {
                return _IDFactura;
            }
            set
            {
                OnIDFacturaChanging(value);
                ReportPropertyChanging("IDFactura");
                _IDFactura = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDFactura");
                OnIDFacturaChanged();
            }
        }
        private global::System.String _IDFactura;
        partial void OnIDFacturaChanging(global::System.String value);
        partial void OnIDFacturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                OnEstatusChanging(value);
                ReportPropertyChanging("Estatus");
                _Estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estatus");
                OnEstatusChanged();
            }
        }
        private global::System.String _Estatus;
        partial void OnEstatusChanging(global::System.String value);
        partial void OnEstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaCreacion;
        partial void OnFechaCreacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaCreacionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SITGPIntegrationModel", "FK_TransaccionVenta_CargaGP", "TransaccionVenta")]
        public EntityCollection<TransaccionVenta> TransaccionVenta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TransaccionVenta>("SITGPIntegrationModel.FK_TransaccionVenta_CargaGP", "TransaccionVenta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TransaccionVenta>("SITGPIntegrationModel.FK_TransaccionVenta_CargaGP", "TransaccionVenta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SITGPIntegrationModel", Name="HCargaGP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HCargaGP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HCargaGP object.
        /// </summary>
        /// <param name="iDCarga">Initial value of the IDCarga property.</param>
        /// <param name="estatus">Initial value of the Estatus property.</param>
        public static HCargaGP CreateHCargaGP(global::System.Int32 iDCarga, global::System.String estatus)
        {
            HCargaGP hCargaGP = new HCargaGP();
            hCargaGP.IDCarga = iDCarga;
            hCargaGP.Estatus = estatus;
            return hCargaGP;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCarga
        {
            get
            {
                return _IDCarga;
            }
            set
            {
                if (_IDCarga != value)
                {
                    OnIDCargaChanging(value);
                    ReportPropertyChanging("IDCarga");
                    _IDCarga = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCarga");
                    OnIDCargaChanged();
                }
            }
        }
        private global::System.Int32 _IDCarga;
        partial void OnIDCargaChanging(global::System.Int32 value);
        partial void OnIDCargaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                OnEstatusChanging(value);
                ReportPropertyChanging("Estatus");
                _Estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estatus");
                OnEstatusChanged();
            }
        }
        private global::System.String _Estatus;
        partial void OnEstatusChanging(global::System.String value);
        partial void OnEstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaCreacion;
        partial void OnFechaCreacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaCreacionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SITGPIntegrationModel", Name="TransaccionVenta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TransaccionVenta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TransaccionVenta object.
        /// </summary>
        /// <param name="iDCarga">Initial value of the IDCarga property.</param>
        /// <param name="iDVenta">Initial value of the IDVenta property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        /// <param name="iDTipo">Initial value of the IDTipo property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        /// <param name="iDLote">Initial value of the IDLote property.</param>
        /// <param name="iDCliente">Initial value of the IDCliente property.</param>
        public static TransaccionVenta CreateTransaccionVenta(global::System.Int32 iDCarga, global::System.Int32 iDVenta, global::System.Int32 tipo, global::System.String iDTipo, global::System.DateTime fecha, global::System.String iDLote, global::System.String iDCliente)
        {
            TransaccionVenta transaccionVenta = new TransaccionVenta();
            transaccionVenta.IDCarga = iDCarga;
            transaccionVenta.IDVenta = iDVenta;
            transaccionVenta.Tipo = tipo;
            transaccionVenta.IDTipo = iDTipo;
            transaccionVenta.Fecha = fecha;
            transaccionVenta.IDLote = iDLote;
            transaccionVenta.IDCliente = iDCliente;
            return transaccionVenta;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCarga
        {
            get
            {
                return _IDCarga;
            }
            set
            {
                OnIDCargaChanging(value);
                ReportPropertyChanging("IDCarga");
                _IDCarga = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCarga");
                OnIDCargaChanged();
            }
        }
        private global::System.Int32 _IDCarga;
        partial void OnIDCargaChanging(global::System.Int32 value);
        partial void OnIDCargaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDVenta
        {
            get
            {
                return _IDVenta;
            }
            set
            {
                if (_IDVenta != value)
                {
                    OnIDVentaChanging(value);
                    ReportPropertyChanging("IDVenta");
                    _IDVenta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDVenta");
                    OnIDVentaChanged();
                }
            }
        }
        private global::System.Int32 _IDVenta;
        partial void OnIDVentaChanging(global::System.Int32 value);
        partial void OnIDVentaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.Int32 _Tipo;
        partial void OnTipoChanging(global::System.Int32 value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IDTipo
        {
            get
            {
                return _IDTipo;
            }
            set
            {
                OnIDTipoChanging(value);
                ReportPropertyChanging("IDTipo");
                _IDTipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IDTipo");
                OnIDTipoChanged();
            }
        }
        private global::System.String _IDTipo;
        partial void OnIDTipoChanging(global::System.String value);
        partial void OnIDTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoDocumento
        {
            get
            {
                return _NoDocumento;
            }
            set
            {
                OnNoDocumentoChanging(value);
                ReportPropertyChanging("NoDocumento");
                _NoDocumento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoDocumento");
                OnNoDocumentoChanged();
            }
        }
        private global::System.String _NoDocumento;
        partial void OnNoDocumentoChanging(global::System.String value);
        partial void OnNoDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AlmacenDefault
        {
            get
            {
                return _AlmacenDefault;
            }
            set
            {
                OnAlmacenDefaultChanging(value);
                ReportPropertyChanging("AlmacenDefault");
                _AlmacenDefault = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AlmacenDefault");
                OnAlmacenDefaultChanged();
            }
        }
        private global::System.String _AlmacenDefault;
        partial void OnAlmacenDefaultChanging(global::System.String value);
        partial void OnAlmacenDefaultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IDLote
        {
            get
            {
                return _IDLote;
            }
            set
            {
                OnIDLoteChanging(value);
                ReportPropertyChanging("IDLote");
                _IDLote = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IDLote");
                OnIDLoteChanged();
            }
        }
        private global::System.String _IDLote;
        partial void OnIDLoteChanging(global::System.String value);
        partial void OnIDLoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IDCliente
        {
            get
            {
                return _IDCliente;
            }
            set
            {
                OnIDClienteChanging(value);
                ReportPropertyChanging("IDCliente");
                _IDCliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IDCliente");
                OnIDClienteChanged();
            }
        }
        private global::System.String _IDCliente;
        partial void OnIDClienteChanging(global::System.String value);
        partial void OnIDClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreCliente
        {
            get
            {
                return _NombreCliente;
            }
            set
            {
                OnNombreClienteChanging(value);
                ReportPropertyChanging("NombreCliente");
                _NombreCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreCliente");
                OnNombreClienteChanged();
            }
        }
        private global::System.String _NombreCliente;
        partial void OnNombreClienteChanging(global::System.String value);
        partial void OnNombreClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoOrden
        {
            get
            {
                return _NoOrden;
            }
            set
            {
                OnNoOrdenChanging(value);
                ReportPropertyChanging("NoOrden");
                _NoOrden = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoOrden");
                OnNoOrdenChanged();
            }
        }
        private global::System.String _NoOrden;
        partial void OnNoOrdenChanging(global::System.String value);
        partial void OnNoOrdenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDMoneda
        {
            get
            {
                return _IDMoneda;
            }
            set
            {
                OnIDMonedaChanging(value);
                ReportPropertyChanging("IDMoneda");
                _IDMoneda = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDMoneda");
                OnIDMonedaChanged();
            }
        }
        private global::System.String _IDMoneda;
        partial void OnIDMonedaChanging(global::System.String value);
        partial void OnIDMonedaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DescuentoComercial
        {
            get
            {
                return _DescuentoComercial;
            }
            set
            {
                OnDescuentoComercialChanging(value);
                ReportPropertyChanging("DescuentoComercial");
                _DescuentoComercial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DescuentoComercial");
                OnDescuentoComercialChanged();
            }
        }
        private Nullable<global::System.Decimal> _DescuentoComercial;
        partial void OnDescuentoComercialChanging(Nullable<global::System.Decimal> value);
        partial void OnDescuentoComercialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Flete
        {
            get
            {
                return _Flete;
            }
            set
            {
                OnFleteChanging(value);
                ReportPropertyChanging("Flete");
                _Flete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flete");
                OnFleteChanged();
            }
        }
        private Nullable<global::System.Decimal> _Flete;
        partial void OnFleteChanging(Nullable<global::System.Decimal> value);
        partial void OnFleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Miscelaneo
        {
            get
            {
                return _Miscelaneo;
            }
            set
            {
                OnMiscelaneoChanging(value);
                ReportPropertyChanging("Miscelaneo");
                _Miscelaneo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Miscelaneo");
                OnMiscelaneoChanged();
            }
        }
        private Nullable<global::System.Decimal> _Miscelaneo;
        partial void OnMiscelaneoChanging(Nullable<global::System.Decimal> value);
        partial void OnMiscelaneoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MontoRecibido
        {
            get
            {
                return _MontoRecibido;
            }
            set
            {
                OnMontoRecibidoChanging(value);
                ReportPropertyChanging("MontoRecibido");
                _MontoRecibido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoRecibido");
                OnMontoRecibidoChanged();
            }
        }
        private Nullable<global::System.Decimal> _MontoRecibido;
        partial void OnMontoRecibidoChanging(Nullable<global::System.Decimal> value);
        partial void OnMontoRecibidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MontoEfectivo
        {
            get
            {
                return _MontoEfectivo;
            }
            set
            {
                OnMontoEfectivoChanging(value);
                ReportPropertyChanging("MontoEfectivo");
                _MontoEfectivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoEfectivo");
                OnMontoEfectivoChanged();
            }
        }
        private Nullable<global::System.Decimal> _MontoEfectivo;
        partial void OnMontoEfectivoChanging(Nullable<global::System.Decimal> value);
        partial void OnMontoEfectivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MontoCheque
        {
            get
            {
                return _MontoCheque;
            }
            set
            {
                OnMontoChequeChanging(value);
                ReportPropertyChanging("MontoCheque");
                _MontoCheque = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoCheque");
                OnMontoChequeChanged();
            }
        }
        private Nullable<global::System.Decimal> _MontoCheque;
        partial void OnMontoChequeChanging(Nullable<global::System.Decimal> value);
        partial void OnMontoChequeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroCheque
        {
            get
            {
                return _NumeroCheque;
            }
            set
            {
                OnNumeroChequeChanging(value);
                ReportPropertyChanging("NumeroCheque");
                _NumeroCheque = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroCheque");
                OnNumeroChequeChanged();
            }
        }
        private global::System.String _NumeroCheque;
        partial void OnNumeroChequeChanging(global::System.String value);
        partial void OnNumeroChequeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Terminos
        {
            get
            {
                return _Terminos;
            }
            set
            {
                OnTerminosChanging(value);
                ReportPropertyChanging("Terminos");
                _Terminos = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Terminos");
                OnTerminosChanged();
            }
        }
        private global::System.String _Terminos;
        partial void OnTerminosChanging(global::System.String value);
        partial void OnTerminosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DescuentoRetornado
        {
            get
            {
                return _DescuentoRetornado;
            }
            set
            {
                OnDescuentoRetornadoChanging(value);
                ReportPropertyChanging("DescuentoRetornado");
                _DescuentoRetornado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DescuentoRetornado");
                OnDescuentoRetornadoChanged();
            }
        }
        private Nullable<global::System.Decimal> _DescuentoRetornado;
        partial void OnDescuentoRetornadoChanging(Nullable<global::System.Decimal> value);
        partial void OnDescuentoRetornadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDComentario
        {
            get
            {
                return _IDComentario;
            }
            set
            {
                OnIDComentarioChanging(value);
                ReportPropertyChanging("IDComentario");
                _IDComentario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDComentario");
                OnIDComentarioChanged();
            }
        }
        private global::System.String _IDComentario;
        partial void OnIDComentarioChanging(global::System.String value);
        partial void OnIDComentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TextoComentario
        {
            get
            {
                return _TextoComentario;
            }
            set
            {
                OnTextoComentarioChanging(value);
                ReportPropertyChanging("TextoComentario");
                _TextoComentario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TextoComentario");
                OnTextoComentarioChanged();
            }
        }
        private global::System.String _TextoComentario;
        partial void OnTextoComentarioChanging(global::System.String value);
        partial void OnTextoComentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notas
        {
            get
            {
                return _Notas;
            }
            set
            {
                OnNotasChanging(value);
                ReportPropertyChanging("Notas");
                _Notas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notas");
                OnNotasChanged();
            }
        }
        private global::System.String _Notas;
        partial void OnNotasChanging(global::System.String value);
        partial void OnNotasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReferenciaCG
        {
            get
            {
                return _ReferenciaCG;
            }
            set
            {
                OnReferenciaCGChanging(value);
                ReportPropertyChanging("ReferenciaCG");
                _ReferenciaCG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReferenciaCG");
                OnReferenciaCGChanged();
            }
        }
        private global::System.String _ReferenciaCG;
        partial void OnReferenciaCGChanging(global::System.String value);
        partial void OnReferenciaCGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Impuestos
        {
            get
            {
                return _Impuestos;
            }
            set
            {
                OnImpuestosChanging(value);
                ReportPropertyChanging("Impuestos");
                _Impuestos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Impuestos");
                OnImpuestosChanged();
            }
        }
        private Nullable<global::System.Decimal> _Impuestos;
        partial void OnImpuestosChanging(Nullable<global::System.Decimal> value);
        partial void OnImpuestosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CostoCobrar
        {
            get
            {
                return _CostoCobrar;
            }
            set
            {
                OnCostoCobrarChanging(value);
                ReportPropertyChanging("CostoCobrar");
                _CostoCobrar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostoCobrar");
                OnCostoCobrarChanged();
            }
        }
        private Nullable<global::System.Decimal> _CostoCobrar;
        partial void OnCostoCobrarChanging(Nullable<global::System.Decimal> value);
        partial void OnCostoCobrarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MontoXCobrar
        {
            get
            {
                return _MontoXCobrar;
            }
            set
            {
                OnMontoXCobrarChanging(value);
                ReportPropertyChanging("MontoXCobrar");
                _MontoXCobrar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoXCobrar");
                OnMontoXCobrarChanged();
            }
        }
        private Nullable<global::System.Decimal> _MontoXCobrar;
        partial void OnMontoXCobrarChanging(Nullable<global::System.Decimal> value);
        partial void OnMontoXCobrarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NCF
        {
            get
            {
                return _NCF;
            }
            set
            {
                OnNCFChanging(value);
                ReportPropertyChanging("NCF");
                _NCF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NCF");
                OnNCFChanged();
            }
        }
        private global::System.String _NCF;
        partial void OnNCFChanging(global::System.String value);
        partial void OnNCFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDVendedor
        {
            get
            {
                return _IDVendedor;
            }
            set
            {
                OnIDVendedorChanging(value);
                ReportPropertyChanging("IDVendedor");
                _IDVendedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDVendedor");
                OnIDVendedorChanged();
            }
        }
        private global::System.String _IDVendedor;
        partial void OnIDVendedorChanging(global::System.String value);
        partial void OnIDVendedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDAyudante
        {
            get
            {
                return _IDAyudante;
            }
            set
            {
                OnIDAyudanteChanging(value);
                ReportPropertyChanging("IDAyudante");
                _IDAyudante = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDAyudante");
                OnIDAyudanteChanged();
            }
        }
        private global::System.String _IDAyudante;
        partial void OnIDAyudanteChanging(global::System.String value);
        partial void OnIDAyudanteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDAyudante2
        {
            get
            {
                return _IDAyudante2;
            }
            set
            {
                OnIDAyudante2Changing(value);
                ReportPropertyChanging("IDAyudante2");
                _IDAyudante2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDAyudante2");
                OnIDAyudante2Changed();
            }
        }
        private global::System.String _IDAyudante2;
        partial void OnIDAyudante2Changing(global::System.String value);
        partial void OnIDAyudante2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorDetail
        {
            get
            {
                return _ErrorDetail;
            }
            set
            {
                OnErrorDetailChanging(value);
                ReportPropertyChanging("ErrorDetail");
                _ErrorDetail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorDetail");
                OnErrorDetailChanged();
            }
        }
        private global::System.String _ErrorDetail;
        partial void OnErrorDetailChanging(global::System.String value);
        partial void OnErrorDetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ruta
        {
            get
            {
                return _Ruta;
            }
            set
            {
                OnRutaChanging(value);
                ReportPropertyChanging("Ruta");
                _Ruta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ruta");
                OnRutaChanged();
            }
        }
        private global::System.String _Ruta;
        partial void OnRutaChanging(global::System.String value);
        partial void OnRutaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Conduce
        {
            get
            {
                return _Conduce;
            }
            set
            {
                OnConduceChanging(value);
                ReportPropertyChanging("Conduce");
                _Conduce = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Conduce");
                OnConduceChanged();
            }
        }
        private global::System.String _Conduce;
        partial void OnConduceChanging(global::System.String value);
        partial void OnConduceChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SITGPIntegrationModel", "FK_TransaccionVenta_CargaGP", "CargaGP")]
        public CargaGP CargaGP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CargaGP>("SITGPIntegrationModel.FK_TransaccionVenta_CargaGP", "CargaGP").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CargaGP>("SITGPIntegrationModel.FK_TransaccionVenta_CargaGP", "CargaGP").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CargaGP> CargaGPReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CargaGP>("SITGPIntegrationModel.FK_TransaccionVenta_CargaGP", "CargaGP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CargaGP>("SITGPIntegrationModel.FK_TransaccionVenta_CargaGP", "CargaGP", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SITGPIntegrationModel", Name="TransaccionVentaItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TransaccionVentaItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TransaccionVentaItem object.
        /// </summary>
        /// <param name="iDVenta">Initial value of the IDVenta property.</param>
        /// <param name="noProducto">Initial value of the NoProducto property.</param>
        /// <param name="unidadMedida">Initial value of the UnidadMedida property.</param>
        /// <param name="cantidad">Initial value of the Cantidad property.</param>
        public static TransaccionVentaItem CreateTransaccionVentaItem(global::System.Int32 iDVenta, global::System.String noProducto, global::System.String unidadMedida, global::System.Double cantidad)
        {
            TransaccionVentaItem transaccionVentaItem = new TransaccionVentaItem();
            transaccionVentaItem.IDVenta = iDVenta;
            transaccionVentaItem.NoProducto = noProducto;
            transaccionVentaItem.UnidadMedida = unidadMedida;
            transaccionVentaItem.Cantidad = cantidad;
            return transaccionVentaItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDVenta
        {
            get
            {
                return _IDVenta;
            }
            set
            {
                if (_IDVenta != value)
                {
                    OnIDVentaChanging(value);
                    ReportPropertyChanging("IDVenta");
                    _IDVenta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDVenta");
                    OnIDVentaChanged();
                }
            }
        }
        private global::System.Int32 _IDVenta;
        partial void OnIDVentaChanging(global::System.Int32 value);
        partial void OnIDVentaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NoProducto
        {
            get
            {
                return _NoProducto;
            }
            set
            {
                if (_NoProducto != value)
                {
                    OnNoProductoChanging(value);
                    ReportPropertyChanging("NoProducto");
                    _NoProducto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NoProducto");
                    OnNoProductoChanged();
                }
            }
        }
        private global::System.String _NoProducto;
        partial void OnNoProductoChanging(global::System.String value);
        partial void OnNoProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UnidadMedida
        {
            get
            {
                return _UnidadMedida;
            }
            set
            {
                if (_UnidadMedida != value)
                {
                    OnUnidadMedidaChanging(value);
                    ReportPropertyChanging("UnidadMedida");
                    _UnidadMedida = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UnidadMedida");
                    OnUnidadMedidaChanged();
                }
            }
        }
        private global::System.String _UnidadMedida;
        partial void OnUnidadMedidaChanging(global::System.String value);
        partial void OnUnidadMedidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                if (_Cantidad != value)
                {
                    OnCantidadChanging(value);
                    ReportPropertyChanging("Cantidad");
                    _Cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cantidad");
                    OnCantidadChanged();
                }
            }
        }
        private global::System.Double _Cantidad;
        partial void OnCantidadChanging(global::System.Double value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrecioUnitario
        {
            get
            {
                return _PrecioUnitario;
            }
            set
            {
                OnPrecioUnitarioChanging(value);
                ReportPropertyChanging("PrecioUnitario");
                _PrecioUnitario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioUnitario");
                OnPrecioUnitarioChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrecioUnitario;
        partial void OnPrecioUnitarioChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioUnitarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescripcionProducto
        {
            get
            {
                return _DescripcionProducto;
            }
            set
            {
                OnDescripcionProductoChanging(value);
                ReportPropertyChanging("DescripcionProducto");
                _DescripcionProducto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescripcionProducto");
                OnDescripcionProductoChanged();
            }
        }
        private global::System.String _DescripcionProducto;
        partial void OnDescripcionProductoChanging(global::System.String value);
        partial void OnDescripcionProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrecioExtendido
        {
            get
            {
                return _PrecioExtendido;
            }
            set
            {
                OnPrecioExtendidoChanging(value);
                ReportPropertyChanging("PrecioExtendido");
                _PrecioExtendido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioExtendido");
                OnPrecioExtendidoChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrecioExtendido;
        partial void OnPrecioExtendidoChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioExtendidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CantidadFacturada
        {
            get
            {
                return _CantidadFacturada;
            }
            set
            {
                OnCantidadFacturadaChanging(value);
                ReportPropertyChanging("CantidadFacturada");
                _CantidadFacturada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CantidadFacturada");
                OnCantidadFacturadaChanged();
            }
        }
        private Nullable<global::System.Double> _CantidadFacturada;
        partial void OnCantidadFacturadaChanging(Nullable<global::System.Double> value);
        partial void OnCantidadFacturadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CantidadCompletada
        {
            get
            {
                return _CantidadCompletada;
            }
            set
            {
                OnCantidadCompletadaChanging(value);
                ReportPropertyChanging("CantidadCompletada");
                _CantidadCompletada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CantidadCompletada");
                OnCantidadCompletadaChanged();
            }
        }
        private Nullable<global::System.Double> _CantidadCompletada;
        partial void OnCantidadCompletadaChanging(Nullable<global::System.Double> value);
        partial void OnCantidadCompletadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CantidadCancelada
        {
            get
            {
                return _CantidadCancelada;
            }
            set
            {
                OnCantidadCanceladaChanging(value);
                ReportPropertyChanging("CantidadCancelada");
                _CantidadCancelada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CantidadCancelada");
                OnCantidadCanceladaChanged();
            }
        }
        private Nullable<global::System.Double> _CantidadCancelada;
        partial void OnCantidadCanceladaChanging(Nullable<global::System.Double> value);
        partial void OnCantidadCanceladaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CantidadBO
        {
            get
            {
                return _CantidadBO;
            }
            set
            {
                OnCantidadBOChanging(value);
                ReportPropertyChanging("CantidadBO");
                _CantidadBO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CantidadBO");
                OnCantidadBOChanged();
            }
        }
        private Nullable<global::System.Double> _CantidadBO;
        partial void OnCantidadBOChanging(Nullable<global::System.Double> value);
        partial void OnCantidadBOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CantidadOrdenada
        {
            get
            {
                return _CantidadOrdenada;
            }
            set
            {
                OnCantidadOrdenadaChanging(value);
                ReportPropertyChanging("CantidadOrdenada");
                _CantidadOrdenada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CantidadOrdenada");
                OnCantidadOrdenadaChanged();
            }
        }
        private Nullable<global::System.Double> _CantidadOrdenada;
        partial void OnCantidadOrdenadaChanging(Nullable<global::System.Double> value);
        partial void OnCantidadOrdenadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CostoUnitario
        {
            get
            {
                return _CostoUnitario;
            }
            set
            {
                OnCostoUnitarioChanging(value);
                ReportPropertyChanging("CostoUnitario");
                _CostoUnitario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostoUnitario");
                OnCostoUnitarioChanged();
            }
        }
        private Nullable<global::System.Double> _CostoUnitario;
        partial void OnCostoUnitarioChanging(Nullable<global::System.Double> value);
        partial void OnCostoUnitarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EntregaDirecta
        {
            get
            {
                return _EntregaDirecta;
            }
            set
            {
                OnEntregaDirectaChanging(value);
                ReportPropertyChanging("EntregaDirecta");
                _EntregaDirecta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntregaDirecta");
                OnEntregaDirectaChanged();
            }
        }
        private Nullable<global::System.Boolean> _EntregaDirecta;
        partial void OnEntregaDirectaChanging(Nullable<global::System.Boolean> value);
        partial void OnEntregaDirectaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ListaPrecio
        {
            get
            {
                return _ListaPrecio;
            }
            set
            {
                OnListaPrecioChanging(value);
                ReportPropertyChanging("ListaPrecio");
                _ListaPrecio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ListaPrecio");
                OnListaPrecioChanged();
            }
        }
        private global::System.String _ListaPrecio;
        partial void OnListaPrecioChanging(global::System.String value);
        partial void OnListaPrecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Almacen
        {
            get
            {
                return _Almacen;
            }
            set
            {
                OnAlmacenChanging(value);
                ReportPropertyChanging("Almacen");
                _Almacen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Almacen");
                OnAlmacenChanged();
            }
        }
        private global::System.String _Almacen;
        partial void OnAlmacenChanging(global::System.String value);
        partial void OnAlmacenChanged();

        #endregion

    
    }

    #endregion

    
}
